"""Updated user and blog models

Revision ID: 4de23318131f
Revises: 51bccf4316a3
Create Date: 2026-01-05 00:34:28.725032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de23318131f'
down_revision = '51bccf4316a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('blog', sa.Column('read_time', sa.Integer(), nullable=True))
    op.add_column('blog', sa.Column('view_count', sa.Integer(), nullable=True))
    op.alter_column('blog', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('user', sa.Column('username', sa.String(), nullable=False))
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('profile_picture', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'profile_picture')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'username')
    op.alter_column('blog', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('blog', 'view_count')
    op.drop_column('blog', 'read_time')
    op.drop_column('blog', 'meta_description')
    # ### end Alembic commands ###
